
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:29:51 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'APUF_64_a8_equal.ucf'
####################################################################################





####################################################################################
# Constraints from file : 'wrapper.ucf'
####################################################################################


#################################################
#Spartan-3A DSP 1800A
#################################################

#NET "tx" LOC = P22;
#NET "rx" LOC = N21;
#NET "clk" LOC = F13;

#################################################
#Spartan-3 1000k Digilent
#################################################



#################################################
#Spartan-3 VTU/MTE board
#################################################

#NET "tx" LOC = P109;
#NET "rx" LOC = P111;
#NET "clk" LOC = P76;

################################################
# Nexys-4 Board
################################################

#NET "clk"   LOC = "E3"	| IOSTANDARD = "LVCMOS33";
#NET "rx"		LOC = "C4"	| IOSTANDARD = "LVCMOS33";		
#NET "tx"		LOC = "D4"	| IOSTANDARD = "LVCMOS33";		



################################################
#chipwhisper  CW3O5 Board  
################################################

#set_property PACKAGE_PIN E3 [get_ports clk]
# D:/DA_PUF_Library-master/DA_PUF_Library-master/FPGA_implementation/XORPUF/src/ucf/wrapper.ucf:38
# The conversion of 'IOSTANDARD' constraint on 'net' object 'clk' has been applied to the port object 'clk'.
#set_property IOSTANDARD LVCMOS33 [get_ports clk]
#set_property PACKAGE_PIN B11 [get_ports rx]
# D:/DA_PUF_Library-master/DA_PUF_Library-master/FPGA_implementation/XORPUF/src/ucf/wrapper.ucf:39
# The conversion of 'IOSTANDARD' constraint on 'net' object 'rx' has been applied to the port object 'rx'.
#set_property IOSTANDARD LVCMOS33 [get_ports rx]
#set_property PACKAGE_PIN A11 [get_ports tx]
# D:/DA_PUF_Library-master/DA_PUF_Library-master/FPGA_implementation/XORPUF/src/ucf/wrapper.ucf:40
# The conversion of 'IOSTANDARD' constraint on 'net' object 'tx' has been applied to the port object 'tx'.
#set_property IOSTANDARD LVCMOS33 [get_ports tx]
#################################################
# arty Spartan-7  board
#################################################

set_property PACKAGE_PIN R2 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN V12 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports rx]

set_property PACKAGE_PIN R12 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]



set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets XAPUF/PUFList[0].APUF/ARBITER/q]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets XAPUF/PUFList[1].APUF/ARBITER/q]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets XAPUF/PUFList[2].APUF/ARBITER/q]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets XAPUF/PUFList[3].APUF/ARBITER/q]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets XAPUF/PUFList[4].APUF/ARBITER/q]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets XAPUF/PUFList[5].APUF/ARBITER/q]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets XAPUF/PUFList[6].APUF/ARBITER/q]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets XAPUF/PUFList[7].APUF/ARBITER/q]